ALTER TYPE "public"."currency" ADD VALUE 'HRK';--> statement-breakpoint
ALTER TYPE "public"."currency" ADD VALUE 'MDL';--> statement-breakpoint
ALTER TYPE "public"."currency" ADD VALUE 'GEL';--> statement-breakpoint
ALTER TYPE "public"."currency" ADD VALUE 'AMD';--> statement-breakpoint
ALTER TYPE "public"."currency" ADD VALUE 'AZN';--> statement-breakpoint
ALTER TYPE "public"."currency" ADD VALUE 'MKD';--> statement-breakpoint
ALTER TYPE "public"."currency" ADD VALUE 'BAM';--> statement-breakpoint
ALTER TYPE "public"."currency" ADD VALUE 'ALL';--> statement-breakpoint
ALTER TYPE "public"."currency" ADD VALUE 'BYN';--> statement-breakpoint
ALTER TYPE "public"."currency" ADD VALUE 'USD';--> statement-breakpoint
ALTER TYPE "public"."currency" ADD VALUE 'CAD';--> statement-breakpoint
ALTER TYPE "public"."currency" ADD VALUE 'MXN';--> statement-breakpoint
ALTER TYPE "public"."currency" ADD VALUE 'BRL';--> statement-breakpoint
ALTER TYPE "public"."currency" ADD VALUE 'ARS';--> statement-breakpoint
ALTER TYPE "public"."currency" ADD VALUE 'CLP';--> statement-breakpoint
ALTER TYPE "public"."currency" ADD VALUE 'COP';--> statement-breakpoint
ALTER TYPE "public"."currency" ADD VALUE 'PEN';--> statement-breakpoint
ALTER TYPE "public"."currency" ADD VALUE 'UYU';--> statement-breakpoint
ALTER TYPE "public"."currency" ADD VALUE 'JPY';--> statement-breakpoint
ALTER TYPE "public"."currency" ADD VALUE 'CNY';--> statement-breakpoint
ALTER TYPE "public"."currency" ADD VALUE 'KRW';--> statement-breakpoint
ALTER TYPE "public"."currency" ADD VALUE 'INR';--> statement-breakpoint
ALTER TYPE "public"."currency" ADD VALUE 'SGD';--> statement-breakpoint
ALTER TYPE "public"."currency" ADD VALUE 'HKD';--> statement-breakpoint
ALTER TYPE "public"."currency" ADD VALUE 'TWD';--> statement-breakpoint
ALTER TYPE "public"."currency" ADD VALUE 'THB';--> statement-breakpoint
ALTER TYPE "public"."currency" ADD VALUE 'MYR';--> statement-breakpoint
ALTER TYPE "public"."currency" ADD VALUE 'IDR';--> statement-breakpoint
ALTER TYPE "public"."currency" ADD VALUE 'PHP';--> statement-breakpoint
ALTER TYPE "public"."currency" ADD VALUE 'VND';--> statement-breakpoint
ALTER TYPE "public"."currency" ADD VALUE 'BDT';--> statement-breakpoint
ALTER TYPE "public"."currency" ADD VALUE 'PKR';--> statement-breakpoint
ALTER TYPE "public"."currency" ADD VALUE 'AUD';--> statement-breakpoint
ALTER TYPE "public"."currency" ADD VALUE 'NZD';--> statement-breakpoint
ALTER TYPE "public"."currency" ADD VALUE 'AED';--> statement-breakpoint
ALTER TYPE "public"."currency" ADD VALUE 'SAR';--> statement-breakpoint
ALTER TYPE "public"."currency" ADD VALUE 'QAR';--> statement-breakpoint
ALTER TYPE "public"."currency" ADD VALUE 'KWD';--> statement-breakpoint
ALTER TYPE "public"."currency" ADD VALUE 'ILS';--> statement-breakpoint
ALTER TYPE "public"."currency" ADD VALUE 'JOD';--> statement-breakpoint
ALTER TYPE "public"."currency" ADD VALUE 'IRR';--> statement-breakpoint
ALTER TYPE "public"."currency" ADD VALUE 'ZAR';--> statement-breakpoint
ALTER TYPE "public"."currency" ADD VALUE 'EGP';--> statement-breakpoint
ALTER TYPE "public"."currency" ADD VALUE 'NGN';--> statement-breakpoint
ALTER TYPE "public"."currency" ADD VALUE 'KES';--> statement-breakpoint
ALTER TYPE "public"."currency" ADD VALUE 'GHS';--> statement-breakpoint
ALTER TYPE "public"."currency" ADD VALUE 'MAD';--> statement-breakpoint
ALTER TYPE "public"."currency" ADD VALUE 'TZS';--> statement-breakpoint
ALTER TYPE "public"."currency" ADD VALUE 'ETB';