/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSitesRouteImport } from './routes/app.sites'
import { Route as AppProductsRouteImport } from './routes/app.products'
import { Route as AppItemsRouteImport } from './routes/app.items'
import { Route as AppCountriesRouteImport } from './routes/app.countries'
import { Route as AppProductProductIdRouteImport } from './routes/app.product.$productId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSitesRoute = AppSitesRouteImport.update({
  id: '/sites',
  path: '/sites',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsRoute = AppProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AppRoute,
} as any)
const AppItemsRoute = AppItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => AppRoute,
} as any)
const AppCountriesRoute = AppCountriesRouteImport.update({
  id: '/countries',
  path: '/countries',
  getParentRoute: () => AppRoute,
} as any)
const AppProductProductIdRoute = AppProductProductIdRouteImport.update({
  id: '/product/$productId',
  path: '/product/$productId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/countries': typeof AppCountriesRoute
  '/app/items': typeof AppItemsRoute
  '/app/products': typeof AppProductsRoute
  '/app/sites': typeof AppSitesRoute
  '/app/product/$productId': typeof AppProductProductIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/countries': typeof AppCountriesRoute
  '/app/items': typeof AppItemsRoute
  '/app/products': typeof AppProductsRoute
  '/app/sites': typeof AppSitesRoute
  '/app/product/$productId': typeof AppProductProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/countries': typeof AppCountriesRoute
  '/app/items': typeof AppItemsRoute
  '/app/products': typeof AppProductsRoute
  '/app/sites': typeof AppSitesRoute
  '/app/product/$productId': typeof AppProductProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/app'
    | '/login'
    | '/signup'
    | '/app/countries'
    | '/app/items'
    | '/app/products'
    | '/app/sites'
    | '/app/product/$productId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/app'
    | '/login'
    | '/signup'
    | '/app/countries'
    | '/app/items'
    | '/app/products'
    | '/app/sites'
    | '/app/product/$productId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/app'
    | '/login'
    | '/signup'
    | '/app/countries'
    | '/app/items'
    | '/app/products'
    | '/app/sites'
    | '/app/product/$productId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/sites': {
      id: '/app/sites'
      path: '/sites'
      fullPath: '/app/sites'
      preLoaderRoute: typeof AppSitesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/products': {
      id: '/app/products'
      path: '/products'
      fullPath: '/app/products'
      preLoaderRoute: typeof AppProductsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/items': {
      id: '/app/items'
      path: '/items'
      fullPath: '/app/items'
      preLoaderRoute: typeof AppItemsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/countries': {
      id: '/app/countries'
      path: '/countries'
      fullPath: '/app/countries'
      preLoaderRoute: typeof AppCountriesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/product/$productId': {
      id: '/app/product/$productId'
      path: '/product/$productId'
      fullPath: '/app/product/$productId'
      preLoaderRoute: typeof AppProductProductIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCountriesRoute: typeof AppCountriesRoute
  AppItemsRoute: typeof AppItemsRoute
  AppProductsRoute: typeof AppProductsRoute
  AppSitesRoute: typeof AppSitesRoute
  AppProductProductIdRoute: typeof AppProductProductIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCountriesRoute: AppCountriesRoute,
  AppItemsRoute: AppItemsRoute,
  AppProductsRoute: AppProductsRoute,
  AppSitesRoute: AppSitesRoute,
  AppProductProductIdRoute: AppProductProductIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
